error: called `unwrap` on `x` after checking its variant with `is_some`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:45:9
   |
LL |     if x.is_some() {
   |     -------------- help: try: `if let Some(<item>) = x`
LL |         x.unwrap();
   |         ^^^^^^^^^^
   |
   = note: `-D clippy::unnecessary-unwrap` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::unnecessary_unwrap)]`

error: called `expect` on `x` after checking its variant with `is_some`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:48:9
   |
LL |     if x.is_some() {
   |     -------------- help: try: `if let Some(<item>) = x`
...
LL |         x.expect("an error message");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:51:9
   |
LL |     if x.is_some() {
   |        ----------- because of this check
...
LL |         x.unwrap();
   |         ^^^^^^^^^^
   |
   = note: `-D clippy::panicking-unwrap` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::panicking_unwrap)]`

error: this call to `expect()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:54:9
   |
LL |     if x.is_some() {
   |        ----------- because of this check
...
LL |         x.expect("an error message");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:58:9
   |
LL |     if x.is_none() {
   |        ----------- because of this check
LL |         x.unwrap();
   |         ^^^^^^^^^^

error: called `unwrap` on `x` after checking its variant with `is_none`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:61:9
   |
LL |     if x.is_none() {
   |     -------------- help: try: `if let Some(<item>) = x`
...
LL |         x.unwrap();
   |         ^^^^^^^^^^

error: called `unwrap` on `x` after checking its variant with `is_some`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:12:13
   |
LL |         if $a.is_some() {
   |         --------------- help: try: `if let Some(<item>) = x`
LL |             $a.unwrap();
   |             ^^^^^^^^^^^
...
LL |     m!(x);
   |     ----- in this macro invocation
   |
   = note: this error originates in the macro `m` (in Nightly builds, run with -Z macro-backtrace for more info)

error: called `unwrap` on `x` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:70:9
   |
LL |     if x.is_ok() {
   |     ------------ help: try: `if let Ok(<item>) = x`
LL |         x.unwrap();
   |         ^^^^^^^^^^

error: called `expect` on `x` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:73:9
   |
LL |     if x.is_ok() {
   |     ------------ help: try: `if let Ok(<item>) = x`
...
LL |         x.expect("an error message");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap_err()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:76:9
   |
LL |     if x.is_ok() {
   |        --------- because of this check
...
LL |         x.unwrap_err();
   |         ^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:79:9
   |
LL |     if x.is_ok() {
   |        --------- because of this check
...
LL |         x.unwrap();
   |         ^^^^^^^^^^

error: this call to `expect()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:82:9
   |
LL |     if x.is_ok() {
   |        --------- because of this check
...
LL |         x.expect("an error message");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: called `unwrap_err` on `x` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:85:9
   |
LL |     if x.is_ok() {
   |     ------------ help: try: `if let Err(<item>) = x`
...
LL |         x.unwrap_err();
   |         ^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:89:9
   |
LL |     if x.is_err() {
   |        ---------- because of this check
LL |         x.unwrap();
   |         ^^^^^^^^^^

error: called `unwrap_err` on `x` after checking its variant with `is_err`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:92:9
   |
LL |     if x.is_err() {
   |     ------------- help: try: `if let Err(<item>) = x`
...
LL |         x.unwrap_err();
   |         ^^^^^^^^^^^^^^

error: called `unwrap` on `x` after checking its variant with `is_err`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:95:9
   |
LL |     if x.is_err() {
   |     ------------- help: try: `if let Ok(<item>) = x`
...
LL |         x.unwrap();
   |         ^^^^^^^^^^

error: this call to `unwrap_err()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:98:9
   |
LL |     if x.is_err() {
   |        ---------- because of this check
...
LL |         x.unwrap_err();
   |         ^^^^^^^^^^^^^^

error: called `unwrap` on `option` after checking its variant with `is_some`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:123:9
   |
LL |     if option.is_some() {
   |     ------------------- help: try: `if let Some(<item>) = &option`
LL |         option.as_ref().unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:126:9
   |
LL |     if option.is_some() {
   |        ---------------- because of this check
...
LL |         option.as_ref().unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: called `unwrap` on `result` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:133:9
   |
LL |     if result.is_ok() {
   |     ----------------- help: try: `if let Ok(<item>) = &result`
LL |         result.as_ref().unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:136:9
   |
LL |     if result.is_ok() {
   |        -------------- because of this check
...
LL |         result.as_ref().unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: called `unwrap` on `option` after checking its variant with `is_some`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:142:9
   |
LL |     if option.is_some() {
   |     ------------------- help: try: `if let Some(<item>) = &mut option`
LL |         option.as_mut().unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:145:9
   |
LL |     if option.is_some() {
   |        ---------------- because of this check
...
LL |         option.as_mut().unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: called `unwrap` on `result` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:151:9
   |
LL |     if result.is_ok() {
   |     ----------------- help: try: `if let Ok(<item>) = &mut result`
LL |         result.as_mut().unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:154:9
   |
LL |     if result.is_ok() {
   |        -------------- because of this check
...
LL |         result.as_mut().unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: called `unwrap` on `option` after checking its variant with `is_some`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:183:17
   |
LL |     if option.is_some() {
   |     ------------------- help: try: `if let Some(<item>) = &option`
LL |         let _ = option.as_ref().unwrap();
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:186:17
   |
LL |     if option.is_some() {
   |        ---------------- because of this check
...
LL |         let _ = option.as_ref().unwrap();
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^

error: called `unwrap` on `result` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:194:9
   |
LL |     if result.is_ok() {
   |     ----------------- help: try: `if let Ok(<item>) = &result`
LL |         let _y = 1;
LL |         result.as_ref().unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:198:9
   |
LL |     if result.is_ok() {
   |        -------------- because of this check
...
LL |         result.as_ref().unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^

error: called `unwrap` on `x` after checking its variant with `is_some`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:224:17
   |
LL |         if x.is_some() {
   |         -------------- help: try: `if let Some(<item>) = x`
LL |             _ = x.unwrap();
   |                 ^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:227:17
   |
LL |         if x.is_some() {
   |            ----------- because of this check
...
LL |             _ = x.unwrap();
   |                 ^^^^^^^^^^

error: called `unwrap` on `r` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:233:17
   |
LL |         if r.is_ok() {
   |         ------------ help: try: `if let Ok(<item>) = &r`
LL |             _ = r.as_ref().unwrap();
   |                 ^^^^^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:236:17
   |
LL |         if r.is_ok() {
   |            --------- because of this check
...
LL |             _ = r.as_ref().unwrap();
   |                 ^^^^^^^^^^^^^^^^^^^

error: called `unwrap` on `x` after checking its variant with `is_some`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:245:17
   |
LL |         if x.is_some() {
   |         -------------- help: try: `if let Some(<item>) = x`
LL |             _ = x.unwrap();
   |                 ^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:248:17
   |
LL |         if x.is_some() {
   |            ----------- because of this check
...
LL |             _ = x.unwrap();
   |                 ^^^^^^^^^^

error: called `unwrap` on `option` after checking its variant with `is_some`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:258:26
   |
LL |     if option.is_some() {
   |     ------------------- help: try: `if let Some(<item>) = option`
LL |         println!("{:?}", option.unwrap());
   |                          ^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:261:26
   |
LL |     if option.is_some() {
   |        ---------------- because of this check
...
LL |         println!("{:?}", option.unwrap());
   |                          ^^^^^^^^^^^^^^^

error: called `unwrap` on `result` after checking its variant with `is_ok`
  --> tests/ui/checked_unwrap/simple_conditionals.rs:268:26
   |
LL |     if result.is_ok() {
   |     ----------------- help: try: `if let Ok(<item>) = result`
LL |         println!("{:?}", result.unwrap());
   |                          ^^^^^^^^^^^^^^^

error: this call to `unwrap()` will always panic
  --> tests/ui/checked_unwrap/simple_conditionals.rs:271:26
   |
LL |     if result.is_ok() {
   |        -------------- because of this check
...
LL |         println!("{:?}", result.unwrap());
   |                          ^^^^^^^^^^^^^^^

error: aborting due to 39 previous errors

